[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]~=5.0"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.setuptools_scm]
write_to = "metricq_source_ipmi/source/version.py"
